apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-green
  namespace: blue-green-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-green
  template:
    metadata:
      labels:
        app: node-app-green
        version: "2.0"
    spec:
      containers:
      - name: node-app
        # This image will be replaced by the Jenkins pipeline
        image: blue-green-app:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000