apiVersion: v1
kind: Service
metadata:
  name: active-service
  namespace: blue-green-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  # Initially, this service points to the BLUE deployment
  selector:
    app: node-app-blue