apiVersion: v1
kind: Service
metadata:
  name: preview-service
  namespace: blue-green-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  # This service will be pointed to the GREEN deployment for testing
  selector:
    app: node-app-green